pull_request_rules:
  - name: Make sure PR are up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions: []
    actions:
      update:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success~=.
    actions:
      merge:
        method: squash
